export const AUTHORITIES = {
  DASHBOARD: {
    DASHBOARD_READ: 'DASHBOARD_READ',
    DASHBOARD_UPDATE: 'DASHBOARD_UPDATE',
    DASHBOARD_ADD: 'DASHBOARD_ADD',
    DASHBOARD_DELETE: 'DASHBOARD_DELETE'
  },
  CONTACT: {
    CONTACT_READ: 'CONTACT_READ',
    CONTACT_UPDATE: 'CONTACT_UPDATE',
    CONTACT_ADD: 'CONTACT_ADD',
    CONTACT_DELETE: 'CONTACT_DELETE'
  },
  USER: {
    USER_READ: 'USER_READ',
    USER_UPDATE: 'USER_UPDATE',
    USER_ADD: 'USER_ADD',
    USER_DELETE: 'USER_DELETE'
  },
  ADMIN: {
    ADMIN_READ: 'ADMIN_READ',
    ADMIN_UPDATE: 'ADMIN_UPDATE',
    ADMIN_ADD: 'ADMIN_ADD',
    ADMIN_DELETE: 'ADMIN_DELETE'
  }
}
